{
  flake.modules.nixos."agdgDiscordBot" =
    # Auto-generated using compose2nix v0.3.2.
    {
      pkgs,
      lib,
      config,
      ...
    }:

    {
      # Runtime
      virtualisation.podman = {
        enable = true;
        autoPrune.enable = true;
        dockerCompat = true;
      };

      # Enable container name DNS for all Podman networks.
      networking.firewall.interfaces =
        let
          matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
        in
        {
          "${matchAll}".allowedUDPPorts = [ 53 ];
        };

      virtualisation.oci-containers.backend = "podman";

      # Containers
      virtualisation.oci-containers.containers."redbot" = {
        image = "phasecorex/red-discordbot";
        environment = {
          "PREFIX" = ".";
          "PUID" = toString config.users.users."redbot".uid;
          "TZ" = "America/Denver";
        };
        environmentFiles = [
          config.clan.core.vars.generators.redbot-token.files."token-env".path
        ];
        volumes = [
          "/var/lib/redbot:/data:rw"
        ];
        log-driver = "journald";
        extraOptions = [
          "--network-alias=redbot"
          "--network=redbot_default"
        ];
      };
      systemd.services."podman-redbot" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
        };
        after = [
          "podman-network-redbot_default.service"
        ];
        requires = [
          "podman-network-redbot_default.service"
        ];
        partOf = [
          "podman-compose-redbot-root.target"
        ];
        wantedBy = [
          "podman-compose-redbot-root.target"
        ];
      };

      # Networks
      systemd.services."podman-network-redbot_default" = {
        path = [ pkgs.podman ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStop = "podman network rm -f redbot_default";
        };
        script = ''
          podman network inspect redbot_default || podman network create redbot_default
        '';
        partOf = [ "podman-compose-redbot-root.target" ];
        wantedBy = [ "podman-compose-redbot-root.target" ];
      };

      # Root service
      # When started, this will automatically create all resources and start
      # the containers. When stopped, this will teardown all resources.
      systemd.targets."podman-compose-redbot-root" = {
        unitConfig = {
          Description = "Root target generated by compose2nix.";
        };
        wantedBy = [ "multi-user.target" ];
      };
    };
}
